############################
# RPM-specific Makefile	   #
# http://yum.pgsqlrpms.org #
#                          #
# Devrim Gunduz            #
# devrim@CommandPrompt.com #
############################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.sles10
SPECFILE="mammoth-replicator.spec"
HOMEDIR=$HOMEDIR

# Now, include global Makefile
include ../../../common/Makefile.global
