############################
# RPM-specific Makefile	   #
# http://yum.pgsqlrpms.org #
#                          #
# Devrim Gunduz            #
# devrim@CommandPrompt.com #
############################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel5
SPECFILE="pgdg-centos-80.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
